# Jekyll 3.x configuration for svenk.org, started 2021-09-23.

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: svenk.org
email: your-email@example.com
description: >-
  This is the website of Sven Köppel
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svenk.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: minima
plugins:
  - jekyll-feed

# do not copy the publications directory
exclude:
   - publications/

# some local blogging
collections:
  posts:
    output: true
    permalink: /posts/:name/
